#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get --app=$app --key=final_path)

#=================================================
# LOAD VALUES
#=================================================

armadietto_config_file="armadietto_config_file.ini"

#=================================================
# SHOW_CONFIG FUNCTION FOR 'SHOW' COMMAND
#=================================================

show_config() {
    if [ -e $armadietto_config_file ]
    then
        ynh_return "YNH_CONFIG_MAIN_CONFIGURATION_IS_SIGNUP=$(cat $armadietto_config_file)"
        ynh_return "YNH_CONFIG_MAIN_CONFIGURATION_IS_PUBLIC=$(cat $armadietto_config_file)"
    fi

    # the default value will be used
}

#=================================================
# MODIFY THE CONFIGURATION
#=================================================

apply_config() {
    echo $YNH_CONFIG_MAIN_CONFIGURATION_IS_SIGNUP > $armadietto_config_file
    echo $YNH_CONFIG_MAIN_CONFIGURATION_IS_PUBLIC > $armadietto_config_file
}

#=================================================
# GENERIC FINALIZATION
#=================================================
case $1 in
    show) show_config;;
    apply) apply_config;;
esac